### ISSUE TITLE
Check preimpoundment CH4 calcs

### ISSUE THREAD

**Issue by tomjanus** [tomjanus/reemission#30]
Logged by @cdb0101 

For preimpoundment CH4 fluxes, we wont have any related to inundated reservoir landcover, as we don't have any reservoir areas situated on organic soils, and there are no non-zero coeffs for mineral soils. However the reemission output gives appreciable preimpoundment CH4 fluxes for several reservoirs. As with the pre-impoundment CO2 calcs, check that heet output fields are coded to correct reservoir landcovers.

**Comment by tomjanus** [comment]
The non-zero preimpoundment emissions (+ve) are due to emissions in the water bodies prior to impoundment. See the code below. For that reason, we can still have non-zero preimpoundment emissions even if the soil type is mineral.
```python
    def ch4_preemission_factor(self, wind_height: float = 50) -> float:
        """Calculate CH4 emission factor the water body, (kg CH4/ha/yr)
        Eq. A.20. in Praire2021.
        This value is used for estimating preimpoundment reservoir CH4
        emissions from water bodies present in the inundated area prior to
        inundation on top of what what's emitted from soil (based on inundated
        soil landcover composition and soil type)
        """
        # Waterbody area is the sum of water areas within the reservoir area
        # prior to impounment (construction of the reservoir)
        waterbody_area = self.wat_area_frac_pre * self.area
        if waterbody_area < 1E-6:
            return 0.0
        ch4_molar = 16  # g/mol
        em_factor = self.surface_ch4_conc(waterbody_area) * \
            self._k600_ch4(
                waterbody_area, self.mean_monthly_windspeed, wind_height) * \
            ch4_molar * 365/100
        # 365 converts from /d to /yr
        # 1/100 converts from 1/km2 to 1/ha
        return em_factor
```

**Comment by cdb0101** [comment]
"The non-zero preimpoundment emissions (+ve) are due to emissions in the water bodies prior to impoundment."

The coding is correct, however this relation is only applicable to existing lakes. It is difficult to estimate areas of pre-impoundment lakes, as we only get a 'total waterbody area' breakdown from heet. In the vast majority of cases these areas pertain only to pre-inundation river areas. Where the areas are greater they reflect older dams (pre2000) where the buffer method should have been used, but was not, thus yielding high areas that reflect the post impoundment reservoir area and not a preexisting lake area. 
Also; these emissions would be positive pre-impoundment, but would cease post impoundment. Thus they would always be substracted from our ultimate GREs sub-model ch4 emission estimates (in the same way that negative landcover fluxes (e.g. for forests) lost due to inundation are Added to final emissions estimates. 
Ultimately, unless code can be written to extract non-river waterbody areas in the inundated area, then we would have to check satellite imagery timeseries (where possible) on a case by case basis to establish whether or not lakes area present. 


Pertinent text from the R calc script (new_ghgEM_script_MY_HP_Dams):

" ### compute CH4 emission for preimpoundment waterbodies - INUNDATED LAKES - Gres approach Rasilo 2015

# compute preimpoundment waterbody area km2 - sum of waterbody LCs for mineral organic and bare areas
# In the case of larger rivers in this dataset the inundated waterbody areas can partly encompass inundation of rivers 
# for which it is not appropriate to apply this relation to (i.e. not lake areas), areas of which have been previously estimated; 
# there are NO clear inundated 'lakes' - thus nothing to compute by this approach herein (HP dams)
# this is difficult to code - and for this dataset the approach below is not taken forward

# several dams yield outputs of significant inundated waterbody areas:
# But none of these have clearly inundated pre-existing lakes.
# These corrections probably need to be assessed on a case by case basis"

**Comment by tomjanus** [comment]
@cdb0101 - We do not only get total water-body area from land use breakdown.

There is an item in the vector of landcover fractions that represents 'wetlands'. See below.
`c_landcover_4 | Landcover category 4 fraction [catchment] | The landcover category 4 ('Wetlands') fraction of the catchment`. This landcover is different from `c_landcover_7` that represents water-bodies.

Pre-impoundment CH4 emissions additionally includes emissions from those wetlands.

In my opinion the methodology for calculating pre-impoundment CH4 emissions in `reemission` is correct and it also follows G-Res.

**Comment by cdb0101** [comment]
We appear to be talking at cross purposes: 

As you say, we have default ipcc emission factors for soil-landcovers in the inundated (pre-impoundment) areas (for both CO2 and CH4), of which wetlands are one such landcover-soil category with associated em factors/rates. 

I am not suggesting at all that these are incorrect or should be omitted. 

I am talking specifically about pre-impoundment emissions from waterbodies in the inundated (pre-impoundment) area- note, wetlands are NOT waterbodies.

 The Gres relation for these waterbodies is specific to lakes ONLY (https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.12741).

 In our datasets for HP and non-HP dams, I could not identify any lakes in the pre-impoundment areas; therefore there are no pre-impoundment waterbody emissions. 
Where we have areas in the heet output pertaining to 'waterbodies', my assessments have found that these are either erroneous (and have been pre-corrected) OR reflect pre-impoundment River (waterbody) areas, which have no associated emissions (or at least means to asses/estimate them). These tend to be the longer valley reservoirs where river areas were sufficient to yield a landcover GIS value to return.

With regard to pre-impoundment fluxes from soil-landcovers:
1. There are no METHANE emissions from mineral soils, only from Organic soils - we have no organic soils in our datasets as far as I am aware, and no pre-impoundment waterbodies,  therefore no pre-impoundment CH4 emissions from either soil-landcovers or waterbodies in our datasets.
2.  There are no CO2 emissions from mineral soils; only sinks. These sinks effectively become emissions in our analyses, as these sinks are lost when the land is flooded. 
3.  There are CO2 emissions from organic soil-landcovers, but we have no organic soils. 

Happy to chat in person to sort this out if needs be : )

**Comment by tomjanus** [comment]
@cdb0101 thanks for the clarification. I followed your recommendation and switched off the G-Res relationship for lakes (set the default to 0) for now. We can add another parameter in the input file, such as *percent of pre-inundation water fraction that is attributed to lakes* and apply the relationship to this area only. In our current case study dataset that parameter would be 0 as we have not found any lakes in the preimpoundment areas.
